import React from "react";
export default function Home() {
        const container: React.CSSProperties = {
            minHeight: "100vh",
                background: "linear-gradient(180deg, #0b0f1a 0%, #070a12 100%)",
                    color: "white",
                        fontFamily:
                              'ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Arial, "Noto Sans", "Liberation Sans", sans-serif',
                                };

                                  const wrap: React.CSSProperties = {
                                      maxWidth: 980,
                                          margin: "0 auto",
                                              padding: "48px 20px",
                                                };

                                                  const pill: React.CSSProperties = {
                                                      display: "inline-flex",
                                                          gap: 8,
                                                              alignItems: "center",
                                                                  padding: "8px 12px",
                                                                      borderRadius: 999,
                                                                          border: "1px solid rgba(255,255,255,0.14)",
                                                                              background: "rgba(255,255,255,0.06)",
                                                                                  fontSize: 13,
                                                                                      letterSpacing: 0.2,
                                                                                        };

                                                                                          const h1: React.CSSProperties = {
                                                                                              fontSize: 44,
                                                                                                  lineHeight: 1.06,
                                                                                                      margin: "18px 0 10px",
                                                                                                          letterSpacing: -0.6,
                                                                                                            };

                                                                                                              const sub: React.CSSProperties = {
                                                                                                                  fontSize: 16,
                                                                                                                      lineHeight: 1.7,
                                                                                                                          color: "rgba(255,255,255,0.78)",
                                                                                                                              maxWidth: 760,
                                                                                                                                  margin: "0 0 22px",
                                                                                                                                    };

                                                                                                                                      const row: React.CSSProperties = {
                                                                                                                                          display: "flex",
                                                                                                                                              flexWrap: "wrap",
                                                                                                                                                  gap: 12,
                                                                                                                                                      margin: "18px 0 26px",
                                                                                                                                                        };

                                                                                                                                                          const btnPrimary: React.CSSProperties = {
                                                                                                                                                              display: "inline-block",
                                                                                                                                                                  padding: "11px 16px",
                                                                                                                                                                      borderRadius: 12,
                                                                                                                                                                          textDecoration: "none",
                                                                                                                                                                              background: "white",
                                                                                                                                                                                  color: "#0b0f1a",
                                                                                                                                                                                      fontWeight: 700,
                                                                                                                                                                                          fontSize: 14,
                                                                                                                                                                                            };

                                                                                                                                                                                              const btnSecondary: React.CSSProperties = {
                                                                                                                                                                                                  display: "inline-block",
                                                                                                                                                                                                      padding: "11px 16px",
                                                                                                                                                                                                          borderRadius: 12,
                                                                                                                                                                                                              textDecoration: "none",
                                                                                                                                                                                                                  border: "1px solid rgba(255,255,255,0.18)",
                                                                                                                                                                                                                      background: "rgba(255,255,255,0.06)",
                                                                                                                                                                                                                          color: "white",
                                                                                                                                                                                                                              fontWeight: 600,
                                                                                                                                                                                                                                  fontSize: 14,
                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                      const grid: React.CSSProperties = {
                                                                                                                                                                                                                                          display: "grid",
                                                                                                                                                                                                                                              gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
                                                                                                                                                                                                                                                  gap: 14,
                                                                                                                                                                                                                                                      marginTop: 22,
                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                          const card: React.CSSProperties = {
                                                                                                                                                                                                                                                              borderRadius: 16,
                                                                                                                                                                                                                                                                  border: "1px solid rgba(255,255,255,0.12)",
                                                                                                                                                                                                                                                                      background: "rgba(255,255,255,0.05)",
                                                                                                                                                                                                                                                                          padding: 16,
                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                              const k: React.CSSProperties = {
                                                                                                                                                                                                                                                                                  fontSize: 12,
                                                                                                                                                                                                                                                                                      color: "rgba(255,255,255,0.65)",
                                                                                                                                                                                                                                                                                          marginBottom: 6,
                                                                                                                                                                                                                                                                                              letterSpacing: 0.2,
                                                                                                                                                                                                                                                                                                  textTransform: "uppercase",
                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                      const v: React.CSSProperties = {
                                                                                                                                                                                                                                                                                                          fontSize: 14,
                                                                                                                                                                                                                                                                                                              lineHeight: 1.6,
                                                                                                                                                                                                                                                                                                                  color: "rgba(255,255,255,0.88)",
                                                                                                                                                                                                                                                                                                                      margin: 0,
                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                          const footer: React.CSSProperties = {
                                                                                                                                                                                                                                                                                                                              marginTop: 34,
                                                                                                                                                                                                                                                                                                                                  paddingTop: 18,
                                                                                                                                                                                                                                                                                                                                      borderTop: "1px solid rgba(255,255,255,0.10)",
                                                                                                                                                                                                                                                                                                                                          display: "flex",
                                                                                                                                                                                                                                                                                                                                              flexWrap: "wrap",
                                                                                                                                                                                                                                                                                                                                                  gap: 14,
                                                                                                                                                                                                                                                                                                                                                      alignItems: "center",
                                                                                                                                                                                                                                                                                                                                                          justifyContent: "space-between",
                                                                                                                                                                                                                                                                                                                                                              color: "rgba(255,255,255,0.6)",
                                                                                                                                                                                                                                                                                                                                                                  fontSize: 12,
                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                      const smallLink: React.CSSProperties = {
                                                                                                                                                                                                                                                                                                                                                                          color: "rgba(255,255,255,0.75)",
                                                                                                                                                                                                                                                                                                                                                                              textDecoration: "none",
                                                                                                                                                                                                                                                                                                                                                                                  borderBottom: "1px solid rgba(255,255,255,0.18)",
                                                                                                                                                                                                                                                                                                                                                                                      paddingBottom: 1,
                                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                                                                              <main style={container}>
                                                                                                                                                                                                                                                                                                                                                                                                    <div style={wrap}>
                                                                                                                                                                                                                                                                                                                                                                                                            <div style={pill}>
                                                                                                                                                                                                                                                                                                                                                                                                                      <span style={{ width: 8, height: 8, borderRadius: 999, background: "#22c55e" }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                <span>ASPIS Network • Deployment Readiness: PRE-DEPLOYMENT</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                <h1 style={h1}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          ASPIS: Adaptive Stability Primitive
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <br />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              for inflation-linked value.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </h1>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p style={sub}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        A protocol-grade stability unit designed to track inflation dynamics with transparent rules,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  constrained governance, and a formal verification gate before mainnet. Built for trust, resilience,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            and fast reaction—without sacrificing auditability.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={row}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <a style={btnPrimary} href="/status">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  View Deployment Status
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <a style={btnSecondary} href="/docs">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Read Docs
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <a style={btnSecondary} href="/security">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Security Model
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={grid}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={card}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={k}>Stability target</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p style={v}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Inflation-reactive unit (IIT) designed for hedging, collateralization, and protocol accounting.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={card}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={k}>Trust & safety</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p style={v}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Immutable Core, hard-coded emergency thresholds, and a mandatory formal verification gate pre-mainnet.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={card}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={k}>Oracles</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p style={v}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Oracle abstraction layer with upgradeable adapters—Core remains untouched as oracle sets evolve.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={card}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={k}>Sentinel layer</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p style={v}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ASPIS Sentinel: monitoring + policy enforcement agent operating above the protocol layer.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={footer}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div>© {new Date().getFullYear()} ASPIS Network</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ display: "flex", gap: 12, flexWrap: "wrap" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a style={smallLink} href="/docs">Docs</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a style={smallLink} href="/status">Status</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a style={smallLink} href="/security">Security</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }